services:
  watchtower:
    image: jplegat/watchtower-riscv64:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    command: glances pihole nginx --interval 129600 --remove-volumes --cleanup